name: tqnia_chat_app_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.0.2
  flutter_screenutil: ^5.9.3
  google_generative_ai: ^0.4.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  flutter_launcher_icons: ^0.14.1 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/app_logo.jpg"
  image_path_ios: "assets/images/app_logo.jpg"
  adaptive_icon_background: "#FFFFFF"   # Background color or image path
  adaptive_icon_foreground: "assets/images/app_logo.jpg"  # Foreground image path

